### ISSUE TITLE
Depth fields

### ISSUE THREAD

**Issue by mullerbsf** [vibansal/crisp#15]
Dear Bansal,

I am still confused about some of the results, as often they seem to not add up. Take the examples below that I retrieved from a representative marker:

FORMAT: GT:GQ:DP:ADf:ADr:ADb

SAMPLE 1: 0/0/0/1/1:0:18:2,3:4,1:0,0
SAMPLE 2: 0/0/1/1/1:3:25:2,9:4,3:0,0

It seems like the total depth is 18 and 25, respectively. The sums of the ADf, ADr and ADb fields, however, are not equal to the total depth.

I appreciate your attention.
Best regards, 
Barbara.

**Comment by vibansal** [comment]
Answered in another issue.
