### ISSUE TITLE
.vcf contains extra tab

### ISSUE THREAD

**Issue by jwbusch0** [vibansal/crisp#22]
Hello vibansal,

I have generated a .vcf using crisp. I was then curious to load that file in vcfR. However, when I tried this, apparently there is an extra tab in the rows with SNP information. This prevents one from loading the .vcf using the vcfR package.

There are easy work arounds, but I thought this might be of interest to developers.

Thank you,
Jeremiah

**Comment by vibansal** [comment]
Thanks. Can you please provide the specific location of the extra tab in the vcf file?

**Comment by jwbusch0** [comment]
Hello,

I looked for the extra tab in linux with "cat -t", and this showed the tabs "^I" and a end line "^M" character. However, I could not find the position of the extra tab.

Jeremiah
________________________________

**Comment by vibansal** [comment]
Fixed in recent updates
