### ISSUE TITLE
Poolsize = 1

### ISSUE THREAD

**Issue by arunkumarramesh** [vibansal/crisp#24]
Hello, Can CRISP be used to call variants in 1000 homozygous samples? So multi-sample but a pool size of 1. I know pool size influences the maf cutoff but I feel like the method should still be OK to use. CRISP is a lot faster in calling SNPs compared to other approaches for 1000 samples. The calls for the sites I have looked at exactly match variant calling with other approaches and Sanger based confirmation. Thanks! Arun.

**Comment by vibansal** [comment]
Yes, it can be used. It works well in diploid samples (pool size = 2).
