### ISSUE TITLE
why can't find AF field for each sample

### ISSUE THREAD

**Issue by Yiguan** [vibansal/crisp#8]
the output VCF body:
`
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  A60_DSW65985-V_HTG27CCXY_L7_all A70_DSW65986-V_HTG27CCXY_L7_all

scf7180000003150|quiver 10520   .       A       G       301     LowDepth        NP=2;DP=4,4,0;VT=SNV;CT=0.0;VP=1;VF=EMpass;AC=200;AF=0.99931;EMstats=30.17:-16.33;HWEstats=-0.0;MQS=0,0,0,9;FLANKSEQ=cggagtgaga:A:gattcgaact    AC:GQ:DP:ADf:ADr:ADb    .:12:7:0,4:0,2:0,0      .:12:2:0,0:0,2:0,0

scf7180000003150|quiver 10530   .       T       C       337     LowDepth        NP=2;DP=3,5,1;VT=SNV;CT=0.0;VP=1;VF=EMpass;AC=200;AF=0.99947;EMstats=33.77:-16.72;HWEstats=-0.0;MQS=0,0,0,9;FLANKSEQ=agattcgaac:T:tccggcccct    AC:GQ:DP:ADf:ADr:ADb    .:13:7:0,3:0,3:0,0      .:13:2:0,0:0,2:0,0
"A60A70.vcf" 1544965L, 392577535C 
`
There are two samples, but AF field only appears in INFO, why can't I find AF in FORMAT for each sample?

**Comment by vibansal** [comment]
If you run with the --EM 0 option, you should get allele frequency for each sample.
